# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/senet_segmentation',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/senet_segmentation',
                'lib_path': 'senet_segmentation'},
  'syms': {'senet_segmentation.core': {'senet_segmentation.core.foo': ('core.html#foo', 'senet_segmentation/core.py')}}}
